on:
  push:
    tags: ["*"]
    branches: ["main"]
  pull_request:

jobs:
  build:
    uses: visciang/gha-elixir-workflow/.github/workflows/elixir.yml@main
    with:
      elixir-version: "1.15.1"
    secrets: inherit
