on:
  push:
    tags: ["*"]
    branches: ["main"]
  pull_request:

jobs:
  build:
    uses: visciang/gha-elixir-workflow/.github/workflows/elixir.yml@v1
    with:
      image: hexpm/elixir:1.16.1-erlang-26.2.2-debian-bookworm-20240130
    secrets: inherit
